"""Prepare deployment files locally. Does not contact or modify the AI server."""
import argparse
import json
import os
import re
import secrets
import subprocess
from pathlib import Path
from urllib.parse import urlsplit
from gateway.settings import APP_IDS, origin

ROOT = Path(__file__).resolve().parent
ORDER = ['dashboard', 'comfy', 'unsloth', 'llm', 'ollama', 'invoke', 'openwebui', 'openclaw']


def protect(directory):
    directory.mkdir(exist_ok=True)
    if os.name == 'nt':
        identity = subprocess.check_output(['whoami'], text=True).strip()
        subprocess.run(['icacls', str(directory), '/inheritance:r', '/grant:r',
                        identity + ':(OI)(CI)F', 'SYSTEM:(OI)(CI)F'],
                       check=True, stdout=subprocess.DEVNULL)
    else:
        directory.chmod(0o700)


def topology(prefix: str, domain: str | None):
    if not re.fullmatch('[a-z][a-z0-9-]{2,35}', prefix):
        raise ValueError('Prefix: 3–36 lowercase letters, digits, hyphens; start with a letter')
    links = {app: origin('https://' + (f'{app}.{domain}' if domain
                                     else f'{prefix}-{app}.onrender.com')) for app in ORDER}
    if domain:
        return links, [(prefix, {url: app for app, url in links.items()})]
    return links, [(f'{prefix}-{app}', {links[app]: app}) for app in ORDER]


def local_targets(config: dict) -> dict:
    targets = {key: f'{urlsplit(value["url"]).scheme}://{urlsplit(value["url"]).netloc}'
               for key, value in config['services'].items()}
    targets.update({'dashboard': f'http://127.0.0.1:{int(config["serverPort"])}',
                    'openwebui': f'http://{config["host"]}:3000',
                    'openclaw': 'http://127.0.0.1:32148'})
    if set(targets) != APP_IDS:
        raise ValueError('Review the configured apps before exporting: unexpected inventory')
    return targets


def blueprint(prefix, deployments, links, domain):
    lines = ['# Generated by setup.py; contains no credentials.',
             f'# Create the {prefix}-login environment group in Render first.', 'services:']
    for name, mapping in deployments:
        lines += ['  - type: web', f'    name: {name}', '    runtime: python',
            '    plan: free', '    numInstances: 1',
            '    branch: codex/render-gateway',
            '    buildCommand: bash build.sh',
            '    startCommand: python -m gateway.server',
            '    healthCheckPath: /_gateway/health', '    autoDeployTrigger: "off"']
        if domain:
            lines += ['    domains:'] + ['      - ' + urlsplit(o).netloc for o in mapping]
        lines += ['    envVars:', f'      - fromGroup: {prefix}-login',
            '      - key: CONNECTOR_TOKEN', '        sync: false',
            '      - key: GATEWAY_ORIGINS', '        value: ' + json.dumps(json.dumps(mapping)),
            '      - key: APP_LINKS', '        value: ' + json.dumps(json.dumps(links))]
    return '\n'.join(lines) + '\n'


def prepare(prefix: str, source: Path, domain: str | None):
    private = ROOT / 'private'
    if (private / 'connector.json').exists():
        raise ValueError('Configuration already exists; preserve its credentials and edit it explicitly')
    config = json.loads(source.read_text(encoding='utf-8-sig'))
    links, deployments = topology(prefix, domain)
    targets = local_targets(config)
    protect(private)
    endpoints = []
    for name, mapping in deployments:
        token = secrets.token_urlsafe(48)
        endpoints.append({'origin': next(iter(mapping)), 'token': token, 'origins': mapping})
        (private / f'{name}.env').write_text('CONNECTOR_TOKEN=' + token + '\n', encoding='utf-8')
    connector = {'targets': targets, 'endpoints': endpoints,
        'ssh': {'key': config['sshKey'], 'target': config['user'] + '@' + config['host']}}
    (private / 'connector.json').write_text(json.dumps(connector, indent=2), encoding='utf-8')
    (ROOT / 'render.yaml').write_text(blueprint(prefix, deployments, links, domain), encoding='utf-8')
    (ROOT / 'callback-urls.txt').write_text('\n'.join(u + '/_gateway/callback' for u in links.values()) + '\n')
    print('Prepared render.yaml and callback-urls.txt. Local credentials are in private/.')
    print('No services started, installed, or changed. Never upload private/.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--prefix', required=True, help='Unique Render service name prefix')
    parser.add_argument('--domain', help='Optional domain, e.g. ai.example.com; one Render service')
    parser.add_argument('--local-config', type=Path,
                        default=Path('C:/AI/AI-Server-Control-Center/config.json'))
    args = parser.parse_args()
    prepare(args.prefix, args.local_config, args.domain)
