"""Outbound-only bridge. Startup never starts/stops/reconfigures an AI workload."""
import argparse
import asyncio
import json
import logging
import random
from pathlib import Path
from urllib.parse import urlsplit
from aiohttp import ClientSession, ClientTimeout, WSMsgType, TCPConnector
from .policy import check_request
from .settings import APP_IDS, PREFIX, origin
from .upstream import proxy_http, proxy_websocket

log = logging.getLogger('connector')


class Connector:
    def __init__(self, config: dict, testing: bool = False):
        self.testing = testing
        self.config = config
        self.targets = config['targets']
        self.tasks = set()
        self.ssh = None
        self.ssh_lock = asyncio.Lock()
        for app_id, base in self.targets.items():
            if app_id not in APP_IDS:
                raise ValueError('Unknown local app')
            parsed = urlsplit(base)
            if parsed.scheme not in {'http', 'https'} or parsed.path not in {'', '/'}:
                raise ValueError('Local targets must be HTTP origins, without paths')
            if parsed.username or parsed.password or parsed.query or parsed.fragment:
                raise ValueError('Local target credentials/query are forbidden')
        for endpoint in config['endpoints']:
            endpoint['origin'] = origin(endpoint['origin'], testing)
            if len(endpoint['token']) < 43:
                raise ValueError('Connector token must be generated by setup.py')
            for public, app_id in endpoint['origins'].items():
                origin(public, testing)
                if app_id not in self.targets:
                    raise ValueError('Origin points to an unconfigured local app')

    async def stream(self, client, endpoint, metadata):
        expected = endpoint['origins'].get(metadata.get('public'))
        if expected != metadata.get('app') or expected not in self.targets:
            raise PermissionError('Origin/application mismatch')
        stream_id = metadata.get('id', '')
        if not stream_id or len(stream_id) > 64 or not all(c.isalnum() or c in '-_' for c in stream_id):
            raise ValueError('Invalid stream identifier')
        url = endpoint['origin'] + PREFIX + '/stream/' + stream_id
        async with client.ws_connect(url, headers={'Authorization': 'Bearer ' + endpoint['token']},
                heartbeat=30, max_msg_size=8 * 1024 * 1024) as tunnel:
            try:
                check_request(expected, metadata['method'], metadata['path'])
                if expected == 'openclaw' and self.config.get('ssh'):
                    await self.ensure_ssh()
                fn = proxy_websocket if metadata.get('upgrade') else proxy_http
                await fn(client, tunnel, metadata, self.targets[expected].rstrip('/'))
            except Exception:
                log.warning('App request failed: %s (details/payload omitted)', expected)
                if not tunnel.closed:
                    await tunnel.send_json({'kind': 'error', 'message':
                        'Local request failed or disconnected. Check status before retrying; the outcome may be unknown.'})

    async def ensure_ssh(self):
        async with self.ssh_lock:
            if self.ssh and self.ssh.returncode is None:
                return
            import os
            config = self.config['ssh']
            command = ['ssh', '-i', os.path.expandvars(config['key']),
                '-o', 'BatchMode=yes', '-o', 'StrictHostKeyChecking=yes',
                '-o', 'ExitOnForwardFailure=yes', '-o', 'ConnectTimeout=5',
                '-o', 'ServerAliveInterval=30', '-o', 'ServerAliveCountMax=3',
                '-N', '-L', '127.0.0.1:32148:127.0.0.1:18789', config['target']]
            kwargs = {'creationflags': 0x08000000} if os.name == 'nt' else {}
            self.ssh = await asyncio.create_subprocess_exec(*command,
                stdout=asyncio.subprocess.DEVNULL, stderr=asyncio.subprocess.DEVNULL, **kwargs)
            await asyncio.sleep(0.7)
            if self.ssh.returncode is not None:
                raise ConnectionError('Read-only OpenClaw SSH tunnel could not open')

    async def endpoint_loop(self, client, endpoint):
        delay = 2
        while True:
            live = set()
            try:
                async with client.ws_connect(endpoint['origin'] + PREFIX + '/connector',
                        headers={'Authorization': 'Bearer ' + endpoint['token']},
                        heartbeat=30, max_msg_size=65536) as control:
                    log.info('Connected: %s', ', '.join(endpoint['origins'].values()))
                    delay = 2
                    await control.send_str('ready')
                    async for message in control:
                        if message.type == WSMsgType.TEXT and len(live) < 24:
                            metadata = json.loads(message.data)
                            task = asyncio.create_task(self.stream(client, endpoint, metadata))
                            live.add(task)
                            task.add_done_callback(lambda t, group=live: self.completed(t, group))
            except Exception:
                log.warning('Gateway offline or authentication rejected; reconnecting later')
            finally:
                for task in live:
                    task.cancel()
                await asyncio.gather(*live, return_exceptions=True)
            await asyncio.sleep(delay + random.random())
            delay = min(delay * 2, 300)

    @staticmethod
    def completed(task, group):
        group.discard(task)
        if not task.cancelled() and task.exception():
            log.warning('Gateway stream rejected or disconnected')

    async def run(self):
        try:
            async with ClientSession(auto_decompress=False, cookie_jar=__import__('aiohttp').DummyCookieJar(),
                    timeout=ClientTimeout(total=None, connect=75),
                    connector=TCPConnector(limit=100)) as client:
                await asyncio.gather(*(self.endpoint_loop(client, e) for e in self.config['endpoints']))
        finally:
            if self.ssh and self.ssh.returncode is None:
                self.ssh.terminate()
                await self.ssh.wait()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--config', default='connector.json')
    parser.add_argument('--apps', help='Comma-separated app IDs to connect; default connects all')
    args = parser.parse_args()
    config = json.loads(Path(args.config).read_text(encoding='utf-8-sig'))
    if args.apps:
        wanted = set(args.apps.split(','))
        if not wanted <= APP_IDS:
            parser.error('Unknown application ID')
        config['endpoints'] = [e for e in config['endpoints']
                               if wanted & set(e['origins'].values())]
    logging.basicConfig(level=logging.INFO, format='%(asctime)s %(levelname)s %(message)s')
    try:
        asyncio.run(Connector(config).run())
    except KeyboardInterrupt:
        print('Remote connector stopped. AI workloads were left running.')


if __name__ == '__main__':
    main()
